# Generated by Django 5.0.4 on 2024-04-03 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Component Type')),
            ],
            options={
                'verbose_name': 'Component Type',
                'verbose_name_plural': 'Component Types',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Product title')),
                ('short_description', models.TextField(verbose_name='Short description')),
                ('image', models.ImageField(upload_to='product/', verbose_name='Product image')),
                ('specifications_url', models.URLField(blank=True, null=True, verbose_name='Specification')),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.componenttype')),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Product title')),
                ('short_description', models.TextField(verbose_name='Short description')),
                ('components', models.ManyToManyField(to='product.component')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Product title')),
                ('short_description', models.TextField(verbose_name='Short description')),
                ('image', models.ImageField(upload_to='product/', verbose_name='Product image')),
                ('specifications_url', models.URLField(blank=True, null=True, verbose_name='Specification')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.configuration')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
