# Generated by Django 5.0.4 on 2024-05-02 17:56

import django.db.models.deletion
import django.utils.timezone
import product.formatChecker
import product.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_device_manual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='image',
        ),
        migrations.RemoveField(
            model_name='device',
            name='manual',
        ),
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='specifications_url',
        ),
        migrations.AddField(
            model_name='component',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='task_creators', to=settings.AUTH_USER_MODEL, verbose_name='Створив'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_creators', to=settings.AUTH_USER_MODEL, verbose_name='Створив'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Product image'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='manual',
            field=product.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=product.models.docs_directory_path, verbose_name='Product manual'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='specifications_url',
            field=models.URLField(blank=True, null=True, verbose_name='Specification'),
        ),
        migrations.AddField(
            model_name='device',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='device_creators', to=settings.AUTH_USER_MODEL, verbose_name='Створив'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(default=453543534, max_length=32, unique=True, verbose_name='Serial number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Product image'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Number of devices')),
                ('short_description', models.TextField(verbose_name='Short description')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_creators', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('devices', models.ManyToManyField(to='product.device')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
            },
        ),
    ]
