# Generated by Django 5.0.4 on 2024-05-10 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_device_image_remove_device_manual_and_more'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='purchase.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('IW', 'In work'), ('CO', 'Configured'), ('TE', 'Tested'), ('AC', 'Accepted from producer'), ('SE', 'Sent to customer'), ('RE', 'Rejected'), ('FI', 'Fixed')], default='CR', max_length=2, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.IntegerField(unique=True, verbose_name='Serial number'),
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
