# Generated by Django 5.0.4 on 2024-06-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_device_order_device_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='creator',
        ),
    ]
