# Generated by Django 5.0.4 on 2024-07-16 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_event_options_alter_event_comment'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='executor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='structure.contractor', verbose_name='Executor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('IW', 'In work'), ('CO', 'Configured'), ('TE', 'Tested'), ('AC', 'Accepted from producer'), ('SE', 'Sent to customer'), ('RE', 'Rejected'), ('FI', 'Fixed')], default='CR', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
