# Generated by Django 5.0.4 on 2024-08-21 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_component_creator_alter_event_date'),
        ('purchase', '0005_alter_order_creator_alter_order_deal_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'pk'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterField(
            model_name='device',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.order'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('IW', 'In work'), ('AC', 'Accepted from producer'), ('CO', 'Configured'), ('TE', 'Tested'), ('RE', 'Rejected'), ('SE', 'Sent to customer'), ('FI', 'Fixed')], default='CR', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(choices=[('IS', 'Issued for work'), ('AC', 'Accepted from producer'), ('CO', 'Configured'), ('TE', 'Tested'), ('RE', 'Rejected'), ('SE', 'Sent to customer'), ('FI', 'Fixed')], default='IS', max_length=2, verbose_name='Event'),
        ),
    ]
