# Generated by Django 5.0.4 on 2024-09-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_device_serial_number_alter_event_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(max_length=30, verbose_name='Status'),
        ),
    ]
