# Generated by Django 5.0.4 on 2025-02-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_device_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('device', 'event')},
        ),
    ]
