# Generated by Django 5.0.4 on 2024-05-10 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_number', models.CharField(max_length=45, verbose_name='Deal number')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price')),
                ('status', models.CharField(choices=[('CR', 'Created'), ('IW', 'In work'), ('AC', 'Accepted from producer'), ('SE', 'Sent to customer')], default='CR', max_length=2, verbose_name='Order status')),
                ('number_of_devices', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of devices')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Comment')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_creators', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-creation_date', 'deal_number'],
            },
        ),
    ]
