# Generated by Django 5.0.4 on 2024-07-15 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_order_customer_alter_order_value'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='structure.company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
