# Generated by Django 5.0.4 on 2024-07-16 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_order_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deal_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
